version: '3'
services:
  mysql:
      image: "mysql:5.7.10"
      ports:
        - "3306:3306"
      env_file: .env
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      volumes:
        - db:/var/lib/mysql
      expose: 
        - 3306
volumes:
  db:
    driver: local