version: '3'
services:

  server:
    image: bnmo-server
    env_file:
      - .env
    ports:
      - "3100:3100"
    depends_on:
      - mysql
    volumes:
      - .:/app
    networks:
    - bnmo-network
  mysql:
    image: "mysql:5.7.10"
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
    - bnmo-network

volumes:
  db:
    driver: local

networks:
  bnmo-network:
    driver: bridge

